export const DEFAULT_CSV = `grade,gender,first,last,email
9,f,Adeline,Stengel,adstengel@amblesidecolorado.com
9,f,Aleya,Stark,astark@amblesidecolorado.com
9,m,Brooks,Lewis,brlweis@amblesidecolorado.com
9,f,Ella,Rodder,erodder@amblesidecolorado.com
9,m,Ethan,Walker,ewalker@amblesidecolorado.com
9,f,Miriam,Lewis,mlewis@amblesidecolorado.com
9,m,Nathaniel,Gardner,ngardner@amblesidecolorado.com
9,m,Noah,Nardella,nonardella@amblesidecolorado.com
9,f,Samara,Ambler,sambler@amblesidecolorado.com
10,m,Jate,Armani,jarmani@amblesidecolorado.com
10,f,Reese,Crawford,rcrawford@amblesidecolorado.com
10,m,Drew,Eskestrand,deskestrand@amblesidecolorado.com
10,f,Anna,Haley,ahaley@amblesidecolorado.com
10,m,Tobiah,Helvig,thelvig@amblesidecolorado.com
10,m,Beck,Johnson,bjohnson@amblesidecolorado.com
10,m,Harrison,Jones,hjones@amblesidecolorado.com
10,f,Abigail,Larson,alarson@amblesidecolorado.com
10,m,Jonah,Muller,jmuller@amblesidecolorado.com
10,f,Phoebe,Nielson,pnielson@amblesidecolorado.com
10,m,Isaiah,Patterson,ipatterson@amblesidecolorado.com
11,f,Eliana,Ambler,eambler@amblesidecolorado.com
11,f,Emma,Betz,ebetz@amblesidecolorado.com
11,f,Abigail,Dantzler,adantzler@amblesidecolorado.com
11,m,Evan,Eskestrand,eeskestrand@amblesidecolorado.com
11,f,Adrianna,Hall,ahall@amblesidecolorado.com
11,f,Carly,Kettler,ckettler@amblesidecolorado.com
11,m,Samuel,Lewis,slewis@amblesidecolorado.com
11,f,Grace,Morris,gmorris@amblesidecolorado.com
11,f,Alexis,Perkins,aperkins@amblesidecolorado.com
11,m,Elijah,Scott,escott@amblesidecolorado.com
11,f,Marley,Scott,mscott@amblesidecolorado.com
11,m,Winston,Stark,wstark@amblesidecolorado.com
12,m,Jackson,Currier,jcurrier@amblesidecolorado.com
12,m,Samuel,Haley,shaley@amblesidecolorado.com
12,m,Isaac,Larson,ilarson@amblesidecolorado.com
12,m,Bradyn,Lewis,blewis@amblesidecolorado.com
12,m,Ethan,Muller,emuller@amblesidecolorado.com
12,m,Nathanael,Nardella,nnardella@amblesidecolorado.com
12,m,Malakhi,Patterson,mpatterson@amblesidecolorado.com
12,m,Isaiah,Perkins,iperkins@amblesidecolorado.com`;
